{ lib, pkgs, inputs, config, ... }:
{
  xdg.dataFile = lib.mkIf config.desktop.enable {
    "wallpapers".source = inputs.gruvbox-wallpapers;
  };
  services.hyprpaper = {
    settings = {
      # ipc = "off";
      preload = [ "~/.cache/wall.png" ];
      wallpaper = [
        "eDP-1,~/.cache/wall.png"
      ];
    };
  };
  wayland.windowManager.hyprland.settings.exec-once = lib.mkIf config.services.hyprpaper.enable [ "swapwallpaper" ];
  home = lib.mkIf config.services.hyprpaper.enable {
    packages = [
      (pkgs.writeShellScriptBin "swapwallpaper" /*sh*/ ''
        paper="''${1:-$(find $HOME/.local/share/wallpapers/wallpapers -type f | grep -v -f '/tmp/badwps' | shuf -n 1)}"
        paper="$(readlink -f $paper)"
        rm ~/.cache/wall.png
        ln -s "$paper" ~/.cache/wall.png
        hyprctl monitors -j | jq -r '.[].name' | xargs -I '{}' hyprctl hyprpaper reload "{},$paper"
      '')
    ];
    file.".config/badwps".text = ''
      \/light\/
      Ubuntu
      ./anime/108948084_p0.png
      ./anime/114133447_p0.png
      ./anime/114753344_p0.png
      ./anime/Kurumi-Ebisuzawa.png
      ./anime/anime_skull.png
      ./anime/glt_gruvbox.png
      ./anime/gruv-wallhaven-011km1.png
      ./anime/gruv-wallhaven-4gmevq.png
      ./anime/gruv-wallhaven-l3y2p2.png
      ./anime/gruv-wallhaven-m9e9m1.png
      ./anime/gruv-wallhaven-pkzoj3.png
      ./anime/gruvbox_girl.png
      ./anime/joyboy.png
      ./anime/komeiji-koishi.png
      ./anime/momo_ayase_centered_gruvbox.png
      ./anime/momo_ayase_gruvbox.png
      ./anime/tanjiro-kamado-gruv.jpg
      ./anime/wall.jpg
      ./anime/wallhaven-2e2xyx.jpg
      ./brands/Manjaro.jpg
      ./brands/Windows-2.png
      ./brands/Windows.png
      ./brands/amdgruvblu.png
      ./brands/amdgruvgreen.png
      ./brands/amdgruvorange.png
      ./brands/amdgruvred.png
      ./brands/apple.jpg
      ./brands/arch-linux.png
      ./brands/awesome.png
      ./brands/dark-intel.png
      ./brands/debian_grey_swirl.png
      ./brands/gruvbox_ubuntu-splash.jpg
      ./brands/gruvbox_ubuntu.png
      ./brands/hewlett-packard.png
      ./brands/netbsd.png
      ./brands/nvgruvgreen.png
      ./brands/wp11058332.png
      ./minimalistic/gruv-wallhaven-4yj28l.png
      ./minimalistic/gruvbox_void_linux.png
      ./minimalistic/hlgruvblu.png
      ./minimalistic/hlgruvgreen.png
      ./minimalistic/hlgruvorange.png
      ./minimalistic/looking-for.png
      ./minimalistic/mustacho.png
      ./minimalistic/red-moon.png
      ./minimalistic/rick.png
      ./minimalistic/solar-system-minimal.png
      ./minimalistic/solar-system.jpg
      ./minimalistic/space-shuttle.png
      ./minimalistic/space.png
      ./minimalistic/starry-sky.png
      ./minimalistic/sunset.png
      ./minimalistic/tetris_gruvbox.png
      ./minimalistic/tetris_gruvbox_brighter.png
      ./minimalistic/this-wallpaper-is-not-available.png
      ./minimalistic/triangle.png
      ./minimalistic/wallhaven-7p6g99.png
      ./minimalistic/zelda.png
      ./minimalistic/zelda_botw.png
      ./mix/hollow-knight.png
      ./mix/landscape0.png
      ./mix/nord-shards.png
      ./mix/random.jpg
      ./mix/rockman.png
      ./mix/wallhaven-z85eoy.jpg
      ./mix/wolf.jpg
      ./painting/The_Artists_Garden_at_Eragny.png
      ./painting/The_Backwater.png
      ./photography/DKoRY7F.jpeg
      ./photography/Excl_Autumn_Leaf.jpg
      ./photography/anna-scarfiello-Pxf5syDVuxQ.jpg
      ./photography/beach.jpg
      ./photography/beach.png
      ./photography/cactus.png
      ./photography/camera-2.jpg
      ./photography/camera.png
      ./photography/canyon.jpg
      ./photography/castle.jpg
      ./photography/cat-2.jpg
      ./photography/cat.jpg
      ./photography/chris-barbalis-rjwU7yqACkY.jpg
      ./photography/chris-lawton-5IHz5WhosQE.jpg
      ./photography/christmas-toys.jpg
      ./photography/dan-otis-OYFHT4X5isg.jpg
      ./photography/daniel-leone-v7daTKlZzaw.jpg
      ./photography/david-lezcano-mNCFOaaLu5o.jpg
      ./photography/elliott-engelmann-DjlKxYFJlTc.jpg
      ./photography/felix-bacher--jEEnRx38wo.jpg
      ./photography/forest-foggy-misty-cloudy.png
      ./photography/forest-moss.png
      ./photography/forest-mountain-cloudy-valley.png
      ./photography/forest-river.jpg
      ./photography/forest.jpg
      ./photography/ganapathy-kumar-JxBcs2O6-C0.jpg
      ./photography/gantaro-9eTP3GF4liQ.jpg
      ./photography/garrett-parker-DlkF4-dbCOU.jpg
      ./photography/girl.jpg
      ./photography/grass.jpg
      ./photography/gruvbox-forest.jpg
      ./photography/house.jpg
      ./photography/houseonthesideofalake.jpg
      ./photography/houssam-korichi-L2BqGjfX-Yw.jpg
      ./photography/hut-2.jpg
      ./photography/hut.jpg
      ./photography/ingo-stiller-3tkxfe2GocY.jpg
      ./photography/jakob-owens-n5wwck8ES4w.jpg
      ./photography/jonas-denil-_PKzBUfuhgg.jpg
      ./photography/kace-rodriguez-p3OzJuT_Dks.jpg
      ./photography/keyboards.jpg
      ./photography/kurt-cotoaga-cqbLg3lZEpk.jpg
      ./photography/lake.png
      ./photography/lights.jpg
      ./photography/maciek-sulkowski-58tP7g7x1LQ.jpg
      ./photography/maciek-sulkowski-GoJIPnqk9e4.jpg
      ./photography/maciek-sulkowski-KvXQBeoolwU.jpg
      ./photography/maciek-sulkowski-XtU9QnauM9k.jpg
      ./photography/maciek-sulkowski-fJ-22PLNGvE.jpg
      ./photography/maciek-sulkowski-jVJWrcUNdeY.jpg
      ./photography/malcolm-lightbody-bngTyBvAkDM.jpg
      ./photography/mate-2.jpg
      ./photography/mate-3.jpg
      ./photography/mate-drink.jpg
      ./photography/mate.jpg
      ./photography/mohammad-alizade-4wzRuAb-KWs.jpg
      ./photography/morning-field.png
      ./photography/mountains2.jpg
      ./photography/nathan-anderson-SAB5Y1HS7NY.jpg
      ./photography/not-so-gruv-city.jpg
      ./photography/octopus.jpg
      ./photography/palms.jpg
      ./photography/peiwen-yu-Etpd8Le6b8E.jpg
      ./photography/persepolis-irl-gruvbox.png
      ./photography/pine-2.jpg
      ./photography/pine.png
      ./photography/pink-abstract.jpg
      ./photography/qJYK2SS.jpeg
      ./photography/railway.jpg
      ./photography/rain.png
      ./photography/river.jpg
      ./photography/road-2.jpg
      ./photography/road-3.jpg
      ./photography/road.jpg
      ./photography/room.jpg
      ./photography/rose.jpg
      ./photography/sea.jpg
      ./photography/seaside.jpg
      ./photography/staircase.jpg
      ./photography/stairs.jpg
      ./photography/street.jpg
      ./photography/sunset-beach.jpg
      ./photography/sunset.jpg
      ./photography/tTIlCNT.jpeg
      ./photography/table.png
      ./photography/teapot-2.jpg
      ./photography/timon-studler--L3q2Uuz6oY.jpg
      ./photography/traf-ukTd6UiQbLQ.jpg
      ./photography/vadim-sherbakov-NQSWvyVRIJk.jpg
      ./photography/waterfall-1.jpg
      ./photography/waterfall-3.jpg
      ./photography/waterfall.jpg
      ./photography/waterfall2.png
      ./photography/wave.jpg
      ./photography/woods.jpg
      ./photography/xander-ashwell-bhTjAUHHvSg.jpg
      ./pixelart/brown_city_planet_w.jpg
      ./pixelart/chinatown.png
      ./pixelart/dock.png
      ./pixelart/girl-reading-book.png
      ./pixelart/gruvbox-pacman-full.png
      ./pixelart/gruvbox-pacman-ghosts.png
      ./pixelart/gruvbox_image11.png
      ./pixelart/gruvbox_image31.png
      ./pixelart/gruvbox_image40.png
      ./pixelart/gruvbox_image44.png
      ./pixelart/leaves-hard-pixelated.png
      ./pixelart/secluded-grove-pixel.png
      ./pixelart/urban_architecture.jpg
      ./pixelart/wallpaper.png
      ./renders/1.jpg
      ./renders/2.jpg
      ./renders/22.jpg
      ./renders/3.jpg
      ./renders/4.jpg
      ./renders/5.jpg
      ./renders/8.jpg
      ./renders/9.jpg
      gruvb_solarsys.png
    '';
  };
}
