# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Root moved off the 128 GB partition on nvme1n1 (LUKS 1354cd7c…, ext4
  # 06fec35a…) on 2026-09-16. It was 94% full with a 75 GB Nix store and no
  # room to grow: the partitions either side of it are swap and /home, so it
  # could not be extended without relocating 532 GB of /home.
  #
  # This is the 507 GB partition on the other NVMe, which was an unused backup
  # volume holding nothing but 145 GB of never-emptied desktop trash. The old
  # root partition is deliberately left untouched and unreferenced, so the
  # older generations in the boot menu still boot the old system.
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/137ff254-7c03-4681-820d-4bc4a33c4da4";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-6eebbd3d-bbdf-440b-980d-2218be1f17e9".device = "/dev/disk/by-uuid/6eebbd3d-bbdf-440b-980d-2218be1f17e9";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DF5C-C6B2";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/ee1099d7-69b1-4d86-886f-7a641b44cf42";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-2b32a316-3fbc-410f-aae1-808ab399d606".device = "/dev/disk/by-uuid/2b32a316-3fbc-410f-aae1-808ab399d606";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/aedca5c5-243f-4c21-aaf1-be378bf42adb"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  hardware.enableRedistributableFirmware = true;


  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
